# Generated by Django 2.2.3 on 2019-07-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_plan_plandetails_planpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeaturs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plandetails',
            name='plan_feature',
        ),
        migrations.AddField(
            model_name='plandetails',
            name='plan_feature',
            field=models.ManyToManyField(null=True, to='services.PlanFeaturs'),
        ),
    ]
