# Generated by Django 2.2.3 on 2019-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190704_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planpay',
            old_name='Plan_pay',
            new_name='plan_pay',
        ),
        migrations.AlterField(
            model_name='plandetails',
            name='plan_feature',
            field=models.ManyToManyField(to='services.PlanFeaturs'),
        ),
    ]
