# Generated by Django 2.2.3 on 2019-07-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190704_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, null=True)),
                ('plan_pay', models.IntegerField(null=True)),
                ('plan_feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.PlanFeaturs')),
            ],
        ),
        migrations.CreateModel(
            name='BasicPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, null=True)),
                ('plan_pay', models.IntegerField(null=True)),
                ('plan_feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.PlanFeaturs')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, null=True)),
                ('plan_pay', models.IntegerField(null=True)),
                ('plan_feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.PlanFeaturs')),
            ],
        ),
        migrations.CreateModel(
            name='UnlimitedPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, null=True)),
                ('plan_pay', models.IntegerField(null=True)),
                ('plan_feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.PlanFeaturs')),
            ],
        ),
        migrations.RemoveField(
            model_name='plandetails',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plandetails',
            name='plan_feature',
        ),
        migrations.RemoveField(
            model_name='plandetails',
            name='planpay',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanDetails',
        ),
        migrations.DeleteModel(
            name='PlanPay',
        ),
    ]
