# Generated by Django 2.2.3 on 2019-07-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190706_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicplan',
            name='plan_feature',
        ),
        migrations.AddField(
            model_name='basicplan',
            name='plan_feature',
            field=models.ManyToManyField(to='services.PlanFeaturs'),
        ),
    ]
