# Generated by Django 2.2.3 on 2019-07-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190706_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceplan',
            name='plan_feature',
        ),
        migrations.AddField(
            model_name='advanceplan',
            name='plan_feature',
            field=models.ManyToManyField(to='services.PlanFeaturs'),
        ),
        migrations.RemoveField(
            model_name='premiumplan',
            name='plan_feature',
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='plan_feature',
            field=models.ManyToManyField(to='services.PlanFeaturs'),
        ),
        migrations.RemoveField(
            model_name='unlimitedplan',
            name='plan_feature',
        ),
        migrations.AddField(
            model_name='unlimitedplan',
            name='plan_feature',
            field=models.ManyToManyField(to='services.PlanFeaturs'),
        ),
    ]
