# Generated by Django 2.2.3 on 2019-07-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(null=True, upload_to='blog')),
                ('blog_title', models.CharField(max_length=50, null=True)),
                ('blog_details', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
