# Generated by Django 2.2.3 on 2019-07-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topslider',
            name='slider_img',
            field=models.ImageField(null=True, upload_to='topslider'),
        ),
    ]
