# Generated by Django 2.2.3 on 2019-07-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190704_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50, null=True)),
                ('service_detail', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
