# Generated by Django 2.2.3 on 2019-07-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('emp_position', models.CharField(max_length=150, null=True)),
                ('emp_photo', models.ImageField(null=True, upload_to='mengallery')),
            ],
        ),
    ]
