# Generated by Django 2.2.3 on 2019-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_employegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatersColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feater_title', models.CharField(max_length=50, null=True)),
                ('feater_dep1', models.CharField(max_length=100, null=True)),
                ('feater_dep2', models.CharField(max_length=100, null=True)),
                ('feater_dep3', models.CharField(max_length=100, null=True)),
                ('feater_dep4', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
