# Generated by Django 2.2.3 on 2019-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_featerscolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_service_title', models.CharField(max_length=20, null=True)),
                ('best_service_details', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
