# Generated by Django 2.2.3 on 2019-07-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_bestservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestServices',
        ),
    ]
